### ISSUE TITLE
overridingErrorMessage should be ported in 2.0

### ISSUE THREAD

**Issue by joel-costigliola** [alexruiz/fest-assert-2.x#12]
For the time being we can't write anymore stuff like :

``` java
assertThat(actual.before(day))
       .overridingErrorMessage("<" + actual + "> is not strictly before <" + day + ">")
       .isTrue();
```

**Comment by php-coder** [comment]
I agree with this. Also, probably method may be renamed to withMessage() ?

**Comment by joel-costigliola** [comment]
I think we will keep `overridingErrorMessage` because it is meaningful (although a little bit long) and it may avoid confusion with `as()`/`describedAs()`. 

A nice thing we could do is to support String.format option, the example would be then

``` java
assertThat(actual.before(day))
       .overridingErrorMessage("<%s> is not strictly before <%s>", actual, day)
       .isTrue();
```

**Comment by ansgarkonermann** [comment]
Heretic's question: what are the use cases for this method? 

The formatting suggestion by joel is beautiful, and the example given pretends we actually do need overridingErrorMessage(). But when dealing with dates, shouldn't we simply provide assertThat(date1).isBefore(date2) and do the formatting of any violation messages inside FEST?

I'm asking myself if this overridingErrorMessage method is used to solve a problem for which better solutions might well exist. I'd even go so far and say using overridingErrorMessage() might resemble a code smell, because either FEST-Assert does not provide a specialized method (and thus could create the message itself) or the author of the assertion statement is not aware of a specialized assert method in FEST and could do without overridingErrorMessage if he knew (and used) the specific assert.

**Comment by joel-costigliola** [comment]
I have got some use cases my heretic friend :).

1 - You are writing a custom assertion class and want to reuse some existing standard assertions but want to easily change the provided error message to be more explicit :

``` java
public PlayerAssert hasNoPreviousTeams() {  
    String errorMessage = format("Expected actual <%s> not to have previous teams but had :\\n%s", 
                          actual, actual.getPreviousTeams());
    // what we must do right now :
    WritableAssertionInfo assertionInfo = new WritableAssertionInfo();
    assertionInfo.overridingErrorMessage(errorMessage);
    Iterables.instance().assertContains(assertionInfo, actual.getTeamMates(), teamMates);

    // what we could do instead  :
    assertThat(actual.getPreviousteams()).overridingErrorMessage(errorMessage).isNotEmpty(); 
    return this;
}
```

2 - You are directly using an assertion and wish to provide a more contextual error message :

``` java
assertThat(player.isRookie()).
           overridingErrorMessage("Expecting Player <%s> to be a rookie but was not.", player).
           isTrue();
```

3 - It should not hurt to provide it and let users choose whether to use it or not (not mentioning the fact that it eases migrating from fest assert 1.x).
