### ISSUE TITLE
Port containsExactly to Fest 2.0

### ISSUE THREAD

**Issue by nfrancois** [alexruiz/fest-assert-2.x#35]
The isEqualTo method allow to verify that the iterable contains exactly some element with order.
This method  only take Iterable argument. Could be interesting to take sequence (a colleague of mine would like)

<code>
Iterable<String> list = list("Yoda", "Luke");
assertThat(list).isEqualsTo("Yoda", "Luke");
</code>

Same for ArrayAssert.
A complementary idea, could be the return of containExactly(...)

**Comment by joel-costigliola** [comment]
It agree, could be nice.

One question though : is the order important is Iterable is a List or if we deal with arrays ?

``` java
Iterable list = list("Yoda", "Luke");
 // OK
assertThat(list).isEqualsTo("Yoda", "Luke");
 // OK or KO ?
assertThat(list).isEqualsTo("Luke", "Yoda");
```

It should probably calls internally containsOnly or containExactly if the order of elements is important.

**Comment by nfrancois** [comment]
``` java
assertThat(list).isEqualsTo("Luke", "Yoda"); // KO
```

Good idea to name it internally containsExactly.

**Comment by kretes** [comment]
I just switched to 2.0 and figured out containsExactly is not there...
containsExactly that is taking a varargs parameter is a must-have. It is much better than wrapping everything in a collection.
It would be great to bring it back to fest 2.0

**Comment by joel-costigliola** [comment]
That's the point of adding `isEqualTo` with a varargs, it is planned for 2.0 (maybe 2.0M6).
The idea there is that `containsExactly` and `isEqualTo` perform the same (two collection are equals if they have the same elements in the same order).

@kretes is it ok for you to have `isEqualTo` instead of `containsExactly` ?

**Comment by kretes** [comment]
Great, that will be enough, I don't mind new naming.

**Comment by nfrancois** [comment]
This method is necessary with array, but with the name <code>isEqualTo(T... values)</code> there is some warning conflict with original <code>isEqualTo(Object[])<code>.
So I think, we should call this method <code> containsExactly</code>. I think also, this method name is more readable and more close to <code>containOnly</code>
@joel-costigliola  What did you think of it ?

**Comment by joel-costigliola** [comment]
@nfrancois 
I have no objection to add `containsExactly`, so let's do it.
We should resolve the conflict between <code>isEqualTo(T... values)</code> and <code>isEqualTo(Object[])</code> by removing <code>isEqualTo(Object[])</code>, since we know that the Iterable has elements fo type T  <code>isEqualTo(Object[])</code> should have been  <code>isEqualTo(T[])</code> which is equivalent to <code>isEqualTo(T... values)</code>.

**Comment by joel-costigliola** [comment]
I have renamed this issue to adress `containsExactly` only and created #59 for  `isEqualTo(T... elements)`
